# This is a basic workflow to help you get started with Actions

name: Create Todays File

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron:  '0 0 * * SUN-SAT'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  schedule:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Set environment variables for dates
        run: |
          CURRENT_DATE_TIME=$(TZ=JST date "+%Y-%m-%d")
          cd Note
          [[ -f $CURRENT_DATE_TIME.md ]] || cp sample.md $CURRENT_DATE_TIME.md
          
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "[bot]: Create note file for $CURRENT_DATE_TIME" && git push || echo "Nothing to commit"
